In [1]:
import numpy as np

In [2]:
# Array declaration
arr = np.array([10,20,30,40])
print("Element at position 2: ",arr[2])

Element at position 2:  30


In [3]:
np.int64(50)

np.int64(50)

In [6]:
print(arr)

[10 20 30 40]


In [7]:
print(arr[1:3])

[20 30]


In [11]:
matrix = np.array([[1,2,3],[4,6,7],[6,8,9]])
print(matrix)

[[1 2 3]
 [4 6 7]
 [6 8 9]]


In [15]:
print(matrix[1,1])

6


In [24]:
print(matrix[0:1,:])

[[1 2 3]]


In [ ]:
arr1 = np.array([1,2,3])
scalar = 5
print(arr1+scalar)

[6 7 8]


In [29]:
arr1

array([6, 7, 8])

In [28]:
arr1 = arr1+scalar
arr1

array([6, 7, 8])

In [31]:
prices = np.array([100,200,300])
dis = np.array([5,10,15]) # %discounts
final_prices = prices * (1-dis/100)
print("Final prices: ",final_prices)

Final prices:  [ 95. 180. 255.]
